# This workflow runs the integration test for the CS326 Scheduler.
# Author: wesdevpro 
# Copyright 2024
name: Build and Run Scheduler Unit Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: |
          gcc -Wall -ansi -lm -o ./tests/unit_tests_runner.exe ./tests/unit_test_driver.c
          ./tests/unit_tests_runner.exe
          echo ""
          echo "Unit Tests Complete"

