# This workflow runs the integration test for the CS326 Scheduler.
# Author: wesdevpro 
# Copyright 2024
name: Scheduler Integration Test 
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
  build:


